language: java
dist: trusty
before_script:
  - psql -c 'create database lavagna;' -U postgres
  - mysql -u root -e 'CREATE DATABASE lavagna CHARACTER SET utf8 COLLATE utf8_bin;'
matrix:
    include:
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=HSQLDB"
          dist: precise
          addons:
              apt:
                  packages:
                      - mysql-server
                      - mysql-client-core-5.5
                      - mysql-client
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=PGSQL-TRAVIS -Dpgsql9.1"
          dist: precise
          addons:
              postgresql: "9.1"
              apt:
                  packages:
                      - mysql-server
                      - mysql-client-core-5.5
                      - mysql-client
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=PGSQL-TRAVIS -Dpgsql9.4"
          dist: precise
          addons:
              postgresql: "9.4"
              apt:
                  packages:
                      - mysql-server
                      - mysql-client-core-5.5
                      - mysql-client
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=MYSQL -Dmysql5.5"
          dist: precise
          addons:
              apt:
                  packages:
                      - mysql-server
                      - mysql-client-core-5.5
                      - mysql-client
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=MYSQL -Dmysql5.6"
          addons:
              apt:
                  packages:
                      - mysql-server-5.6
                      - mysql-client-core-5.6
                      - mysql-client-5.6
        - jdk: oraclejdk8
          env: PROFILE="-Ddatasource.dialect=MYSQL -Dmariadb10.1"
          addons:
              mariadb: 10.1
script: mvn test jacoco:report $PROFILE
after_success:
  - mvn coveralls:report
sudo: required
